### ISSUE TITLE
Maven support for Java module

### ISSUE THREAD

**Issue by brsanthu** [google/diff-match-patch#1]
Is adding support for Maven for Java module is in scope for this project? That should greatly help adopt this library easily by users.

I can help contribute the initial version if you going to PR.

**Comment by NeilFraser** [comment]
I actually just removed Maven support a few days ago:
https://github.com/google/diff-match-patch/commit/e04089e0ea035c6093af3939643d9518bad02416

My reason was that I didn't know if it was still used and I didn't want to accumulate abandoned packaging services.  Your request appears to validate that it is still used.  I'm not a Java person, so I'd appreciate a PR to set this up appropriately.

**Comment by brsanthu** [comment]
@NeilFraser I have raised https://github.com/google/diff-match-patch/pull/2. Please take a look and comment there. I will close this issue now.
