### ISSUE TITLE
Structured content demo

### ISSUE THREAD

**Issue by thewebartisan7** [google/diff-match-patch#109]
There is a demo of structured content from docs here https://github.com/google/diff-match-patch/wiki/Plain-Text-vs.-Structured-Content ?

Thanks

**Comment by dmsnell** [comment]
@thewebartisan7 what exactly are you wanting to know? what kind of example are you expecting or wanting?

**Comment by thewebartisan7** [comment]
Quoting from docs the first method:

> One method is to strip the tags from the HTML using a simple regex or node-walker. Then diff the HTML content against the text content. Don't perform any diff cleanups. This diff enables one to map character positions from one version to the other (see the diff_xIndex function). After this, one can apply all the patches one wants against the plain text, then safely map the changes back to the HTML. The catch with this technique is that although text may be freely edited, HTML tags are immutable.
