### ISSUE TITLE
Port C++ code to use Qt5 and its QStringRef

### ISSUE THREAD

**Issue by nurupo** [google/diff-match-patch#12]
Qt4 is no longer supported by Qt.

Apart from that, porting to Qt5 should also improve the performance, as it has added QStringRef class and QString::leftRef, QString::midRef and QString::rightRef methods. I see that the code splits QStrings into substrings quite a lot, and it does so by making copies, but with QStringRef you can avoid making copies since QStringRef substrings reference the original QString.

**Comment by NeilFraser** [comment]
I'd much rather port the C++ code to use the STL.  Qt seems like a terrible mistake in terms of maintainability and performance.

**Comment by nurupo** [comment]
If the code doesn't need any text encoding functionality, e.g. UTF-8, then yes, an STL-only version would be much appreciated. Qt is a rather big dependency, which might discourage the use of the library.

**Comment by data-man** [comment]
https://github.com/QuentinFiard/diff_match_patch
https://github.com/leutloff/diff-match-patch-cpp-stl
