### ISSUE TITLE
AST differencing 

### ISSUE THREAD

**Issue by yehyaali151989w** [google/diff-match-patch#125]
Hi All,
Thanks for your work!

I would like to implement an ast diff in JavaScript programs

Could you please guide me to how to use it?

Thanks in advances

**Comment by dmsnell** [comment]
@yehyaali151989w this library probably isn't what you're looking for since it's focused on text diffing. AST diffing or graph diffing is a much more complicated topic. you may have interest in checking out what the folks at https://github.com/Wilfred/difftastic have done.
