### ISSUE TITLE
Difficult to set up efficiently with diff_main!!

### ISSUE THREAD

**Issue by jungjin09** [google/diff-match-patch#148]
Hi,
from this code:
```
std::wstring para{ L"Twas brillig, and the slithy toves Did gyre and gimble in the wabe. All mimsy were the borogroves,\n
And the mome dang phoung raths outgrabe." };

int k = dmp.match_main(para, L"đan phượng",100); ->this return 112 as expected. [dang phoung]
but dmp.diff_main(para, L"đan phượng"); returns very different results. It is far from the search position.
```

![image](https://github.com/google/diff-match-patch/assets/99936463/c8cdd6b3-5eaa-4d80-bb92-d1bc6fdafcc0)

My wish is to extract and return the string that needs to be edited as "dang phoung", 
How do I set it up to achieve it?

Thanks you!

**Comment by dmsnell** [comment]
@dangdkhanh you can try diffing in line mode, which is one of the options, but there's no guarantee on how the diff returns. `diff-match-patch` produces a diff that is somewhere between a minimal diff (which tends to be completely unreadable from a human standpoint) and a human diff (which tends to be less deterministic and may increase the edit script).

as `match_main` doesn't include the length of the matched segment, it's not usable to extract the text.

**Comment by jungjin09** [comment]
Thank you @dmsnell 
Great . I will try this option.
