### ISSUE TITLE
Implicit declaration of function 'check_string' is invalid in C99

### ISSUE THREAD

**Issue by mrkizy** [google/diff-match-patch#23]
when I use cocoapods to download diff-match-patch, and compile my project, it failed, error is "Implicit declaration of function 'check_string' is invalid in C99" why?

**Comment by NeilFraser** [comment]
Can you leave a note as to how this problem was resolved?  In case anyone else runs into it.

I have no expertise in Objective C or cocoapods, so I can't comment.

**Comment by mrkizy** [comment]
the sdk's version is so low that xcode warns these errors, i update the lastet version
