### ISSUE TITLE
%0A in output

### ISSUE THREAD

**Issue by cpovirk** [google/diff-match-patch#4]
I encountered this in Java (using `patch_toText(patch_make(...))`, but I can see it on the JavaScript demo page, too, and I saw [a past Google Code discussion](https://web.archive.org/web/20161231095031/https://code.google.com/archive/p/google-diff-match-patch/issues/3) touch on it for a Python usage, plus [some Go code](https://github.com/shazow/go-diff/blob/b6b7b6733b8c9589e2452df9345ddaf75badd0db/dmp/differ.go#L41) working around it.

Enter the following into [the demo page](https://neil.fraser.name/software/diff_match_patch/demos/patch.html):

Old version:
> a
> a

New version:
> a
> a
> a

(I entered both with trailing newlines, but the behavior is similar without.)

Compute Patch gives:

```
@@ -1,4 +1,6 @@
 a%0Aa%0A
+a%0A
```

I would have expected something more like:

```
$ diff -u <(echo a; echo a) <(echo a; echo a; echo a) | tail -n +3
@@ -1,2 +1,3 @@
 a
 a
+a
```

(Hmm, I notice only now that diff-match-match disagrees with `diff -u` about the number of lines involved. (At least, I think that's what the ,4/,6 and ,2/,3 are?))

As a workaround, I can replace %0A sequences with the empty string, but as best I can tell, even that will leave various other characters escaped.

I'm a little confused as to why URL encoding comes into this at all. I would expect for `Patch.toString()` to avoid all that, instead looking like this:

```
        text.append(aDiff.text.replaceAll("\n", ""))                                                                                                          
            .append("\n");                    
```

(It seems strange that I need to remove internal \n characters at all. I haven't dug into it.)

**Comment by cpovirk** [comment]
Just got back to this.

`patch` does understand the format produced by `diff-match-patch`. I am confused about this, since it's not clear how `patch` differentiates between actual sequences of `%0A` and those intended as newlines. Possibly it's based on the counts given by the line numbers, or it might just do whatever works. I couldn't find anything in [the GNU description](http://www.gnu.org/software/diffutils/manual/html_node/Detailed-Unified.html) or [Guido's description](https://www.artima.com/weblogs/viewpost.jsp?thread=164293).

Also, I'm wrong about both the workaround and my proposed change to `Patch.toString()`. (I had written some tests, and I think I was looking at the expected values rather than the actual....) If I remove all \n characters, I end up with the lines run together. And if I replace them with newlines, I end up with lines without the appropriate leading characters, plus some extra newlines:

```
 a
a

-m
n
o
p
+q
r
s
t
u
v

z
z
```

Then, if I remove `append("\n")` from `Patch.toString()`, I can eliminate the blank lines -- but also the newline between `p` and `+q`. (And I'd still need to reinsert the + and - signs.)

**Comment by cpovirk** [comment]
Maybe I should look at it as "`diff-match-patch` does all kinds of fun stuff that is overkill for line-based diffs; for those, use [java-diff-utils](https://code.google.com/archive/p/java-diff-utils/) or something."

**Comment by NeilFraser** [comment]
The root issue here is that DMP is character-based, whereas Unix diff/patch is line based.  There's documentation on this here:  https://github.com/google/diff-match-patch/wiki/Unidiff
