### ISSUE TITLE
Memory Error while doing some diffs

### ISSUE THREAD

**Issue by satheesh1997** [google/diff-match-patch#42]

**Comment by NeilFraser** [comment]
What language?
What were the inputs?
What's the exact error traceback?

**Comment by satheesh1997** [comment]
The language is python2

text_1 = '(236181595,237994730,240888080),(236181595,237994730,249798276),(236181595,237994730,258031525),(236181595,237994730,264205312),(236181595,237994730,247304608),(236181595,237994730,288889638),(236181595,237994730,264768724),(236181595,237994730,241962810),(236181595,237994730,278222334),(236181595,237994730,256754366),(236181595,237994730,271674117),(236181595,237994730,279732201),(236181595,23799'

text_2 = '92064689'


I just got Memory error exception it was from line number 277

**Comment by NeilFraser** [comment]
From the command line I executed python 2.7:
```
Python 2.7.10 (default, Oct  6 2017, 22:29:07) 
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.31)] on darwin

import diff_match_patch as dmp_module
dmp = dmp_module.diff_match_patch()
text_1 = '(236181595,237994730,240888080),(236181595,237994730,249798276),(236181595,237994730,258031525),(236181595,237994730,264205312),(236181595,237994730,247304608),(236181595,237994730,288889638),(236181595,237994730,264768724),(236181595,237994730,241962810),(236181595,237994730,278222334),(236181595,237994730,256754366),(236181595,237994730,271674117),(236181595,237994730,279732201),(236181595,23799'
text_2 = '92064689'
diff = dmp.diff_main(text_1, text_2)
```
The result of `diff` was:
```
[(-1, '(2361815'), (0, '9'), (-1, '5,'), (0, '2'), (-1, '37994730,240888'), (0, '0'), (-1, '80),(23'), (0, '6'), (-1, '181595,23799'), (0, '4'), (-1, '730,249798276),(23'), (0, '6'), (-1, '1'), (0, '8'), (-1, '1595,237994730,258031525),(236181595,237994730,264205312),(236181595,237994730,247304608),(236181595,237994730,288889638),(236181595,237994730,264768724),(236181595,237994730,241962810),(236181595,237994730,278222334),(236181595,237994730,256754366),(236181595,237994730,271674117),(236181595,237994730,279732201),(236181595,2379'), (0, '9')]
```

I'm not seeing any memory error, nor a reason for one to appear.  This is a very small diff.  Maybe the rest of your program eating up memory, and the diff is just the final straw that pushes it over the edge?
