### ISSUE TITLE
related to extra character ¶...

### ISSUE THREAD

**Issue by Neha-Baldaniya** [google/diff-match-patch#44]
In my requirement I don’t want to display this "¶"extra character.

Based on my findings I found that specific code has been placed in **diff_match_patch_uncompressed.js** file.

But I don't want to display it during comparison, So can I remove it from file or it is placed purpose fully.

**Comment by NeilFraser** [comment]
From the documentation:

> diff_prettyHtml(diffs) → html
> Takes a diff array and returns a pretty HTML sequence. This function is mainly intended as an example from which to write ones own display functions.

It is a trivial function, and everyone wants a completely different output style.  Just write your own visualization code.
