### ISSUE TITLE
Word level comparison instead of character level

### ISSUE THREAD

**Issue by XinyiYS** [google/diff-match-patch#45]
For example:
String_1 :  I included an apple in my basket.
String_2: I introduced apple to my basketball friend.

The resulted diffs are:
<img width="335" alt="screen shot 2018-09-15 at 5 37 27 pm" src="https://user-images.githubusercontent.com/17292375/45584900-0dfa7a80-b90e-11e8-8adc-fcc2b52bdea3.png">

I wonder if there are ways to mark the word "included" entirely as deletion and then "introduced" as an insertion, instead of breaking them up into differing or non-differing characters.

**Comment by NeilFraser** [comment]
https://github.com/google/diff-match-patch/wiki/Line-or-Word-Diffs

**Comment by XinyiYS** [comment]
Thanks for the link. 

I may still need some help with it.
So I changed the part of:
lineEnd = -1
      while lineEnd < len(text) - 1:
        lineEnd = text.find('\n', lineStart)
        if lineEnd == -1:
          lineEnd = len(text) - 1
        line = text[lineStart:lineEnd + 1]
        lineStart = lineEnd + 1

To:
      wordStart = 0
      wordEnd = -1
      while wordEnd < len(text) - 1:
        if ' ' in text:
          wordEnd = text.find(' ', wordStart)
        else:
          wordEnd = text.find('\n',wordStart)
        if wordEnd == -1:
          wordEnd = len(text) - 1
        word = text[wordStart:wordEnd + 1]
        wordStart = wordEnd + 1

The diff results still missed some words, and especially strings that include numbers, like the years. 
"2017" -> "2018"  only recognises "7" -> "8", which is not very helpful. I wonder if I am doing something wrong or maybe missed something.
