### ISSUE TITLE
Is this project still maintained?

### ISSUE THREAD

**Issue by franklinyu** [google/diff-match-patch#46]
I don't see issues and pull requests replied. Is there any intent to keep maintain it?

**Comment by nihlaakram** [comment]
Yes, this project is still maintained. You can find the closed issues in [[1] ](https://github.com/google/diff-match-patch/issues?q=is%3Aissue+is%3Aclosed)and closed/merged pull requests in [[2] ](https://github.com/google/diff-match-patch/pulls?q=is%3Apr+is%3Aclosed)

**Comment by franklinyu** [comment]
Closing. Latest reaction is https://github.com/google/diff-match-patch/issues/45#issuecomment-421632177, not very long ago.
