### ISSUE TITLE
Possible to get diff and use diff2html

### ISSUE THREAD

**Issue by rickywu** [google/diff-match-patch#62]
I tried use diff2html render diff result but sometimes the result is not correct,  
Is this possible?
https://github.com/rtfpessoa/diff2html

```
       let patchUntil = new diff_match_patch();
        let diffMain = patchUntil.diff_main(firstDescribe, secondDescribe);
        patchUntil.diff_cleanupSemantic(diffMain);
        let patchMake = patchUntil.patch_make(firstDescribe, secondDescribe);
        let patchToText = patchUntil.patch_toText(patchMake);
        // let patches = patchUntil.patch_fromText(patchToText);
        // let app=patchUntil.patch_apply(patches, firstDescribe);
        let strInput = "--- compare\n+++ compare\n" + patchToText;

        let outputHtml = Diff2Html.getPrettyHtml(strInput, {
          inputFormat: "diff",
          outputFormat: this.outputFormat,
          matching: "lines"
        });
        this.outputHtml = outputHtml;
```

**Comment by rickywu** [comment]
var dmp = new diff_match_patch();
        var a = dmp.diff_linesToChars_(firstDescribe, secondDescribe);
        var lineText1 = a.chars1;
        var lineText2 = a.chars2;
        var lineArray = a.lineArray;
        var diffs = dmp.diff_main(lineText1, lineText2, false);
        dmp.diff_charsToLines_(diffs, lineArray);
        console.info(diffs);
        let patchMake = dmp.patch_make(firstDescribe,diffs);
        console.info(patchMake)
        let patchToText = dmp.patch_toText(patchMake);

        let strInput = "--- compare\n+++ compare\n" + patchToText;
        strInput = decodeURIComponent(strInput);
        let outputHtml = Diff2Html.getPrettyHtml(strInput, {
          inputFormat: "diff",
          outputFormat: this.outputFormat,
          matching: "lines"
        });
        this.outputHtml = outputHtml;

**Comment by geyuqiu** [comment]
@rickywu where did you look up for Patch-API-Doc ?
[The Doc about Patch](https://github.com/google/diff-match-patch/wiki/API#patch_maketext1-text2--patches) isn't fairly clear :(
