### ISSUE TITLE
cleanupSemantic doesnt return anything

### ISSUE THREAD

**Issue by jdruiter** [google/diff-match-patch#64]
The last part of the example doesn't work because cleanupSemantic doesn't return the result.

I looked at the code and indeed the function doesn't return anything.

**Comment by NeilFraser** [comment]
Which example?

**Comment by cnrtsvr** [comment]
diff_cleanupSemantic function doesn't return the result. It gets the diffs(Array of 'diff_match_patch.Diff') and makes the changes in that array.

You should just call it with diffs as parameter and your diffs array will be cleaned up and you can.

**Comment by PeterPorzuczek** [comment]
I think this issue should be closed
