### ISSUE TITLE
Is there solution for diff markdown text ?

### ISSUE THREAD

**Issue by icksky** [google/diff-match-patch#7]
I want to diff the text with markdown mark. Is there  a solution ?
Thanks.

**Comment by whitecolor** [comment]
@NeilFraser 

Hi, would be really interesting to get the comment on this, is diff-match-path would be a decent solution in case of markdown content?

**Comment by mgrandi** [comment]
Why wouldn't it work? it works fine, Joplin (https://joplinapp.org/) just added support for versioned notes using this library , and joplin uses markdown

**Comment by icksky** [comment]
@mgrandi Thank you, but sorry, I don't find how to compare the note in Joplin

**Comment by Ggayane** [comment]
Hi, does anyone found a solution to this? I want to have diff of HTMLTexts
