### ISSUE TITLE
patch format doubt

### ISSUE THREAD

**Issue by xiao623** [google/diff-match-patch#71]
When I generate a patch file in Linux Ubuntu, I get some cases:
@@ -12,12 +13,35 @@ OBJS = \
or @@ ... @@ ..\n
the second @@ has some chars after it sometimes.

Is the patch file wrong? But I generate it in Linux System using diff command.
if it is correct， these code don't support the case:
diff_match_patch.java:2225
```
    Pattern patchHeader
        = Pattern.compile("^@@ -(\\d+),?(\\d*) \\+(\\d+),?(\\d*) @@$");
```

**Comment by xiao623** [comment]
And I change the regex to ^@@ -(\\d+),?(\\d*) \\+(\\d+),?(\\d*) @@.*$ to support the case.

**Comment by NeilFraser** [comment]
The patch format used by Diff Match Patch has differences from the Unidiff format.  See this page: https://github.com/google/diff-match-patch/wiki/Unidiff
