### ISSUE TITLE
Unclearness in docs

### ISSUE THREAD

**Issue by amatiash** [google/diff-match-patch#75]
In wiki https://github.com/google/diff-match-patch/wiki/Plain-Text-vs.-Structured-Content
it is defined: `This library handles exact matches...` and `...this library only supports fuzzy matches...`.

Seems confusing for me. Can you please clarify it?

**Comment by Jacko1394** [comment]
This library supports **exact match and fuzzy match**.

Fuzzy match only works for plain text;
Exact match works for all content, text and binary.

**Comment by amatiash** [comment]
Ok, thanks!
