### ISSUE TITLE
相同内容对比，Java和OC返回结果不一致！这样的问题该怎样解决？Compared with the same content, Java and OC return results are inconsistent! How can such a problem be solved?

### ISSUE THREAD

**Issue by xuxh6** [google/diff-match-patch#76]
Compared with the same content, Java and OC return results are inconsistent! How can such a problem be solved?（相同内容对比，Java和OC返回结果不一致！这样的问题该怎样解决？
![Andios](https://user-images.githubusercontent.com/18001416/63663126-c05fe080-c7f3-11e9-8b63-83f990297722.jpg)
）Java on the left and OC on the right

**Comment by xuxh6** [comment]
OC和CPP返回的结果是一致的！java和他们不一样！对比算法是一致的吗？（OC and CPP return the same results! Java is different from them! Is the comparison algorithm consistent?）

**Comment by xuxh6** [comment]
@NeilFraser

**Comment by xuxh6** [comment]
调用diffs之前再调用一次这个diff_cleanupSemantic

**Comment by xuxh6** [comment]
调用diffs之前再调用一次diff_cleanupSemanticLossless

**Comment by prorigorous** [comment]
@xuxh6 请问在使用OC版本的时候是要给DiffMatchPatch.m文件添加MRC的flag？
