### ISSUE TITLE
Are there any performance benchmarks or results available?

### ISSUE THREAD

**Issue by StingyJack** [google/diff-match-patch#77]
These don't need to be exact or precise, I just need to know roughly how long it should take to diff something like two 50k word documents. Could it be measured in seconds, minutes, hours, etc.?

I can measure for myself, but it's my results that are taking what feels like far too long and I also do not know what is a reasonable expectation for this topic.

**Comment by NeilFraser** [comment]
Every language has a speedtest in its tests directory.  This is a real-world relatively complex 12kb diff (taken from an actual Wikipedia edit).  Here are the current benchmarks for the speedtest:
https://docs.google.com/spreadsheets/d/1zpZccuBpjMZTvL1nGDMKJc7rWL_m_drF4XKOJvB27Kc/edit#gid=0
Note that performance varies wildly between languages.  The compiled languages (e.g. C) are orders of maginitude faster than the interpreted languages (e.g. Python).

Performance is really important to DMP (second only to correctness).  Please reopen this issue if you have further performance-related questions.
