### ISSUE TITLE
del and ins tag are not recognized by Swing components 

### ISSUE THREAD

**Issue by GuillaumeRobbe** [google/diff-match-patch#8]
Hello,

When using diff_prettyHtml it appears that the generated html is not recognized by Swing components. 

I fixed it by replacing del and ins tag by span and adding the style attibutes text-decoration:underline when adding and text-decoration:line-through when deleting.

Here is the complete code: 

```
case INSERT:
        html.append("<span style=\"background-color:#e6ffe6;text-decoration:underline\">")
            .append(text)
            .append("</span>");
        break;
case DELETE:
        html.append("<span style=\"background-color:#ffe6e6;text-decoration:line-through\">")
            .append(text)
            .append("</span>");
        break;
```

I hope this will help people using your awesome project.

**Comment by NeilFraser** [comment]
Yes, that's exactly what one is supposed to do.  As the documentation says, "This function is mainly intended as an example from which to write ones own display functions."
